<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cliente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cliente_model');
        $this->load->library('form_validation');
        

    } 

    /*
     * Listing of tb_clientes
     */
    function index()
    {
        $this->load->database();
        $data['tb_clientes'] = $this->Cliente_model->get_all_tb_clientes();
        //$data['_view'] = 'cliente/index';
        $this->load->view('cliente',$data);
    }

    /*
     * Listing details of tb_clientes
     */
    function detail($clientes_id)
    {
        $this->load->database();
        $data['tb_cliente'] = $this->Cliente_model->get_tb_cliente($clientes_id);
        
        if(isset($data['tb_cliente']['clientes_id']))
        {

            $this->load->view('cliente_detail',$data);
        } 
        else
        {
            redirect('/cliente/index');
            //$this->load->view('cliente');  
        } 
    }

    /*
     * Adding a new tb_cliente
     */
    function add()
    {   
        $this->load->database();
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'clientes_imobiliaria' => $this->input->post('clientes_imobiliaria'),
				'clientes_nome' => $this->input->post('clientes_nome'),
				'clientes_rg' => $this->input->post('clientes_rg'),
				'clientes_tipo_pessoa' => $this->input->post('clientes_tipo_pessoa'),
				'clientes_cpf_cnpj' => $this->input->post('clientes_cpf_cnpj'),
				'clientes_nacionalidade' => $this->input->post('clientes_nacionalidade'),
				'clientes_naturalidade' => $this->input->post('clientes_naturalidade'),
				'clientes_cep' => $this->input->post('clientes_cep'),
				'clientes_rua' => $this->input->post('clientes_rua'),
				'clientes_numero' => $this->input->post('clientes_numero'),
				'clientes_complemento' => $this->input->post('clientes_complemento'),
				'clientes_bairro' => $this->input->post('clientes_bairro'),
				'clientes_cidade' => $this->input->post('clientes_cidade'),
				'clientes_estado' => $this->input->post('clientes_estado'),
				'clientes_pais' => $this->input->post('clientes_pais'),
				'clientes_telefone' => $this->input->post('clientes_telefone'),
                'clientes_celular' => $this->input->post('clientes_celular'),
                'clientes_email' => $this->input->post('clientes_email'),
                'clientes_anotacao' => $this->input->post('clientes_anotacao'),
            );
            
            //print_r($params);
            $tb_cliente_id = $this->Cliente_model->add_tb_cliente($params);
            redirect('cliente/index');
        }
        else
        {            
            //$data['_view'] = 'cliente/add';
            $this->load->view('cliente_add');
        }
    }  

    /*
     * Editing a tb_cliente
     */
    function edit($clientes_id)
    {   
        // check if the tb_cliente exists before trying to edit it
        $this->load->database();
        $data['tb_cliente'] = $this->Cliente_model->get_tb_cliente($clientes_id);
        
        if(isset($data['tb_cliente']['clientes_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'clientes_imobiliaria' => $this->input->post('clientes_imobiliaria'),
					'clientes_nome' => $this->input->post('clientes_nome'),
					'clientes_rg' => $this->input->post('clientes_rg'),
					'clientes_tipo_pessoa' => $this->input->post('clientes_tipo_pessoa'),
					'clientes_cpf_cnpj' => $this->input->post('clientes_cpf_cnpj'),
					'clientes_nacionalidade' => $this->input->post('clientes_nacionalidade'),
					'clientes_naturalidade' => $this->input->post('clientes_naturalidade'),
					'clientes_cep' => $this->input->post('clientes_cep'),
					'clientes_rua' => $this->input->post('clientes_rua'),
					'clientes_numero' => $this->input->post('clientes_numero'),
					'clientes_complemento' => $this->input->post('clientes_complemento'),
					'clientes_bairro' => $this->input->post('clientes_bairro'),
					'clientes_cidade' => $this->input->post('clientes_cidade'),
					'clientes_estado' => $this->input->post('clientes_estado'),
					'clientes_pais' => $this->input->post('clientes_pais'),
					'clientes_anotacao' => $this->input->post('clientes_anotacao'),
                );

                $this->Cliente_model->update_tb_cliente($clientes_id,$params);            
                redirect('cliente/index');
            }
            else
            {
                //$data['_view'] = 'cliente/edit';
                $this->load->view('cliente_add',$data);
            }
        }
        else
            show_error('The tb_cliente you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_cliente
     */
    function remove($clientes_id)
    {
        $tb_cliente = $this->Cliente_model->get_tb_cliente($clientes_id);

        // check if the tb_cliente exists before trying to delete it
        if(isset($tb_cliente['clientes_id']))
        {
            $this->Cliente_model->delete_tb_cliente($clientes_id);
            redirect('cliente/index');
        }
        else
            show_error('The tb_cliente you are trying to delete does not exist.');
    }
    
    /**
     * ajaxGetClient method
     * @return JSON Acess example:  'success' : function(data){  
     *                              var result = JSON.parse( data );                             	                        
     *	                            $('#result').html( '<p>'+ result.tb_cliente.clientes_id +'</p>' ); 
     */
    function ajaxGetClientByCPF($clientes_id)
    {		
        
        //Connect to database
        $this->load->database();
        
        //Call model for this id  
        $ClienteData['tb_cliente'] = $this->Cliente_model->get_tb_cliente($clientes_id);
        
        
        if(isset($ClienteData['tb_cliente']['clientes_id']))
        {
            echo json_encode( $ClienteData );
            //echo json_encode( array( 'date' => date( 'H:i:s' ) ) );
        } 
        else
         {
            //$ClienteData = '0';
            //echo json_encode( $ClienteData );
         }
          
         
        
        
    }
    
}
