<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imovel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Imoveis_model');
    } 

    /*
     * Listing of tb_imoveis
     */
    function index()
    {
        $this->load->database();
        //$data['tb_imoveis'] = $this->Imoveis_model->get_all_tb_imoveis();

        //$data['_view'] = 'imovel/index';
        $this->load->view('imovel');
    }

    /*
     * Adding a new tb_imovel
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'imoveis_imobiliaria' => $this->input->post('imoveis_imobiliaria'),
				'imoveis_proprietario' => $this->input->post('imoveis_proprietario'),
				'imoveis_cep' => $this->input->post('imoveis_cep'),
				'imoveis_rua' => $this->input->post('imoveis_rua'),
				'imoveis_numero' => $this->input->post('imoveis_numero'),
				'imoveis_complemento' => $this->input->post('imoveis_complemento'),
				'imoveis_bairro' => $this->input->post('imoveis_bairro'),
				'imoveis_cidade' => $this->input->post('imoveis_cidade'),
				'imoveis_estado' => $this->input->post('imoveis_estado'),
				'imoveis_pais' => $this->input->post('imoveis_pais'),
				'imoveis_sala' => $this->input->post('imoveis_sala'),
				'imoveis_dormitorio' => $this->input->post('imoveis_dormitorio'),
				'imoveis_suite' => $this->input->post('imoveis_suite'),
				'imoveis_cozinha' => $this->input->post('imoveis_cozinha'),
				'imoveis_banheiro' => $this->input->post('imoveis_banheiro'),
				'imoveis_condominio' => $this->input->post('imoveis_condominio'),
				'imoveis_anotacao' => $this->input->post('imoveis_anotacao'),
            );
            
            $tb_imovel_id = $this->Imoveis_model->add_tb_imovel($params);
            redirect('imovel/index');
        }
        else
        {            
            //$data['_view'] = 'imovel/add';
            $this->load->view('imovel_add');
        }
    }  

    /*
     * Editing a tb_imovel
     */
    function edit($imoveis_id)
    {   
        // check if the tb_imovel exists before trying to edit it
        $data['tb_imovel'] = $this->Imoveis_model->get_tb_imovel($imoveis_id);
        
        if(isset($data['tb_imovel']['imoveis_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'imoveis_imobiliaria' => $this->input->post('imoveis_imobiliaria'),
					'imoveis_proprietario' => $this->input->post('imoveis_proprietario'),
					'imoveis_cep' => $this->input->post('imoveis_cep'),
					'imoveis_rua' => $this->input->post('imoveis_rua'),
					'imoveis_numero' => $this->input->post('imoveis_numero'),
					'imoveis_complemento' => $this->input->post('imoveis_complemento'),
					'imoveis_bairro' => $this->input->post('imoveis_bairro'),
					'imoveis_cidade' => $this->input->post('imoveis_cidade'),
					'imoveis_estado' => $this->input->post('imoveis_estado'),
					'imoveis_pais' => $this->input->post('imoveis_pais'),
					'imoveis_sala' => $this->input->post('imoveis_sala'),
					'imoveis_dormitorio' => $this->input->post('imoveis_dormitorio'),
					'imoveis_suite' => $this->input->post('imoveis_suite'),
					'imoveis_cozinha' => $this->input->post('imoveis_cozinha'),
					'imoveis_banheiro' => $this->input->post('imoveis_banheiro'),
					'imoveis_condominio' => $this->input->post('imoveis_condominio'),
					'imoveis_anotacao' => $this->input->post('imoveis_anotacao'),
                );

                $this->Imoveis_model->update_tb_imovel($imoveis_id,$params);            
                redirect('imovel/index');
            }
            else
            {
                $data['_view'] = 'imovel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_imovel you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_imovel
     */
    function remove($imoveis_id)
    {
        $tb_imovel = $this->Imoveis_model->get_tb_imovel($imoveis_id);

        // check if the tb_imovel exists before trying to delete it
        if(isset($tb_imovel['imoveis_id']))
        {
            $this->Imoveis_model->delete_tb_imovel($imoveis_id);
            redirect('imovel/index');
        }
        else
            show_error('The tb_imovel you are trying to delete does not exist.');
    }
    
    
    
}
