<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imoveis_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_imovel by imoveis_id
     */
    function get_tb_imovel($imoveis_id)
    {
        return $this->db->get_where('tb_imoveis',array('imoveis_id'=>$imoveis_id))->row_array();
    }
    
    /*
     * Get all tb_imoveis
     */
    function get_all_tb_imoveis()
    {
        return $this->db->get('tb_imoveis')->result_array();
    }
    
    /*
     * function to add new tb_imovel
     */
    function add_tb_imovel($params)
    {
        $this->db->insert('tb_imoveis',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_imovel
     */
    function update_tb_imovel($imoveis_id,$params)
    {
        $this->db->where('imoveis_id',$imoveis_id);
        $response = $this->db->update('tb_imoveis',$params);
        if($response)
        {
            return "tb_imovel updated successfully";
        }
        else
        {
            return "Error occuring while updating tb_imovel";
        }
    }
    
    /*
     * function to delete tb_imovel
     */
    function delete_tb_imovel($imoveis_id)
    {
        $response = $this->db->delete('tb_imoveis',array('imoveis_id'=>$imoveis_id));
        if($response)
        {
            return "tb_imovel deleted successfully";
        }
        else
        {
            return "Error occuring while deleting tb_imovel";
        }
    }
}
